### ISSUE TITLE
Validar aplicativo com Késia.

### ISSUE THREAD

**Issue by v1d3rm3** [ccsa-ufrn/manual-do-aluno#2]
Ainda é necessário marcar uma reunião com Késia para validar o aplicativo. @marconiccsa @mrmorais 

Por favor, colocar detalhes do andamento aqui.

**Comment by mrmorais** [comment]
Késia recomendou algumas alterações
- Alteração do ícone #8
- Alteração da splashscreen #9
- Criação de uma área para CA #10
