### ISSUE TITLE
Compactação de imagens

### ISSUE THREAD

**Issue by v1d3rm3** [ccsa-ufrn/manual-do-aluno#4]
Acredito que as imagens podem ser compactadas, estão muito grandes.
Por exemplo, na entrada do aplicativo, aquelas imagens que estão como opções não precisam ter o tamanho que têm, podem ser diminuídas, caso da: 'O que tem no ccsa?' (127kb, 600px x 175px)...

Favor, verificar.

**Comment by mrmorais** [comment]
Imagens compactadas
